// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZ_-VSQkrE9sojZkKfCK87XpqLdps0dY',
    appId: '1:629433156796:web:b6c8fb6d0346fd794fbcb9',
    messagingSenderId: '629433156796',
    projectId: 'nomikai-6a1cb',
    authDomain: 'nomikai-6a1cb.firebaseapp.com',
    storageBucket: 'nomikai-6a1cb.appspot.com',
    measurementId: 'G-39MTGQ9P7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJSY2IWyzUmxcqKNu-gBDpmxqoe8I9hzY',
    appId: '1:629433156796:android:587e958e712f329f4fbcb9',
    messagingSenderId: '629433156796',
    projectId: 'nomikai-6a1cb',
    storageBucket: 'nomikai-6a1cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCaUsmmUy-ASX_EnCLzlJiD9_ZMFFHX7Q',
    appId: '1:629433156796:ios:f00e21ad4ef79d9b4fbcb9',
    messagingSenderId: '629433156796',
    projectId: 'nomikai-6a1cb',
    storageBucket: 'nomikai-6a1cb.appspot.com',
    iosClientId: '629433156796-grc3q7u6lamc8rtjuu193gld4qrbk6f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nomikai',
  );
}
